name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Conda environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: etl-number
          python-version: 3.11
          auto-activate-base: false

      - name: Install dependencies
        run: |
          source $CONDA/etc/profile.d/conda.sh
          conda activate etl-number || conda create --name etl-number python=3.11 -y && conda activate etl-number
          pip install -r requirements.txt
          python setup.py build_ext --inplace

      - name: Run tests and extract duration
        run: |
          source $CONDA/etc/profile.d/conda.sh
          conda activate etl-number
          pytest_output=$(python -m pytest _etl_a9number_v4.py)
          duration=$(echo "$pytest_output" | grep -oP '\d+\.\d+(?=s$)')
          echo "Test duration: ${duration}s"
          echo "TEST_DURATION=${duration}" >> $GITHUB_ENV

      - name: Create test duration badge
        uses: emibcn/badge-action@v2
        with:
          label: "Test Time"
          status: "${{ env.TEST_DURATION }}s"
          color: blue
          path: test-duration-badge.svg

      - name: Upload test duration badge as artifact
        uses: actions/upload-artifact@v4
        with:
          name: test-duration-badge
          path: test-duration-badge.svg